### ISSUE TITLE
Dockerfileの更新

### ISSUE THREAD

**Issue by bcts369** [lcnem/identity#17]
基本的にUbuntu対応だけだが、コマンドのコピー先を変えることも検討。

> COPY --from=build-env /go/bin/identityd /usr/bin/identityd

コピー先を `/usr/local/bin` した方が良いのではないか？

**Comment by bcts369** [comment]
@KimuraYu45z 

コピー先を /usr/local/bin に変更しても良いですか？

**Comment by bcts369** [comment]
Alpineでビルドしたバイナリを、Ubuntuで利用するという記述ミスがあるので修正します。

イメージのビルドにはリポジトリ内の `Dockerfile` が使われていると思っていたが、実は `docker pull` コマンドが走っていたため、正常な動作確認ができていなかった。

**Comment by bcts369** [comment]
@KimuraYu45z 過去のAlpineを使ったビルド方法でも特に問題ないと思いますが、 AlpineからUbuntuへ変更する理由ってなんでしたっけ？

過去のDockerfile
https://github.com/lcnem/identity/blob/90c6dfb4f86060731dd31151ce52190c94022c03/Dockerfile

**Comment by kimurayu45z** [comment]
naoさんがやりにくいとおっしゃったからなので、ぼくはalpineのままいい（過去のをリストアでいい）とおもいます。

**Comment by bcts369** [comment]
@KimuraYu45z お気遣いありがとうございます。以前のVPSは実験もかねて使ってよいとのことだったので、やりにくいためUnuntuにさせていただきましたが、今回は本番稼働をを視野に入れてるはずなので、コンテナ運用以外は基本的に行いませんので、Alpineでいいかなと思います。

ということですので、 Alpine 用の設定に戻しますね。Makefileによるコマンド生成は今回は入れないことにします。

**Comment by kimurayu45z** [comment]
あざます！
