### ISSUE TITLE
チェイン（ノード）用のDockerfileを更新する

### ISSUE THREAD

**Issue by bcts369** [lcnem/identity#9]
imageをalpineから、ubuntuに変更する。

それによって起動方法が変わるので、ドキュメントを変更するか、docker-compose.ymlを作って指定する。

 完了したらPRする。

**Comment by bcts369** [comment]
@KimuraYu45z 関連イシューのリンク（1 - 複数）を貼るというルールだとまとめておけるのですが、このタスクに書くことは好ましくないですか？

**Comment by kimurayu45z** [comment]
それでもおｋです。

**Comment by bcts369** [comment]
@KimuraYu45z 了解しました。では、このまま続けてみます。

**Comment by kimurayu45z** [comment]
完了
